{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "42e53c22",
   "metadata": {},
   "source": [
    "# 03 - Model Training & Comparison\n",
    "\n",
    "This notebook trains machine learning models on gene expression and miRNA datasets to classify Primary Myelofibrosis (PMF) vs control samples.\n",
    "\n",
    "The objective is to compare predictive performance across the two molecular data types.\n",
    "\n",
    "Key steps:\n",
    "- Load aligned gene expression and miRNA datasets\n",
    "- Load corresponding metadata with labels\n",
    "- Construct feature matrices (X) and target vectors (y)\n",
    "- Compare high-dimensional gene expression and miRNA feature spaces\n",
    "- Perform stratified cross-validation\n",
    "- Perform leakage-safe feature selection within each cross-validation fold\n",
    "- Apply feature scaling within each fold\n",
    "- Train Logistic Regression and Random Forest classifiers\n",
    "- Generate out-of-fold predictions and probability scores\n",
    "- Compare model performance using ROC-AUC, accuracy, precision, recall, and F1\n",
    "- Save cross-validation results and out-of-fold predictions for downstream evaluation"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "63b739be",
   "metadata": {},
   "source": [
    "### Import Required Libraries"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a0583e02",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "import os\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.model_selection import StratifiedKFold, cross_validate, cross_val_predict\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.feature_selection import SelectKBest, f_classif\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.metrics import (\n",
    "    accuracy_score,\n",
    "    roc_auc_score,\n",
    "    precision_score,\n",
    "    recall_score,\n",
    "    f1_score\n",
    ")\n",
    "\n",
    "# Add project root to system path for module imports\n",
    "sys.path.append(os.path.abspath(\"..\"))\n",
    "\n",
    "# Import custom functions for metadata extraction and parsing\n",
    "from Src.Model_Utility import evaluate_model"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9655efe7",
   "metadata": {},
   "source": [
    "### Load Aligned Expression and Metadata"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "0ed211c3",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load aligned gene expression dataset\n",
    "gene_df = pd.read_csv(\"../Data/Processed/gene_expression_aligned.csv\", index_col=0)\n",
    "\n",
    "# Load gene expression metadata\n",
    "meta_gene = pd.read_csv(\"../Data/Processed/gene_metadata.csv\", index_col=0)\n",
    "\n",
    "# Load aligned miRNA expression dataset\n",
    "mirna_df = pd.read_csv(\"../Data/Processed/mirna_expression_aligned.csv\", index_col=0)\n",
    "\n",
    "# Load miRNA expression metadata\n",
    "meta_mirna = pd.read_csv(\"../Data/Processed/mirna_metadata.csv\", index_col=0)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "570fb0f6",
   "metadata": {},
   "source": [
    "### Prepare Features and Labels\n",
    "\n",
    "Separate input features (X) and target labels (y) for both gene expression and miRNA datasets.\n",
    "\n",
    "- Features (X): expression values\n",
    "- Labels (y): disease classification (PMF vs Control)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "2a13472e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Gene expression shape: (73, 49386)\n",
      "miRNA expression shape: (73, 20212)\n",
      "\n",
      "Gene expression class distribution:\n",
      "1    42\n",
      "0    31\n",
      "Name: count, dtype: int64\n",
      "\n",
      "miRNA class distribution:\n",
      "1    42\n",
      "0    31\n",
      "Name: count, dtype: int64\n",
      "\n",
      "Sample alignment: False\n",
      "Gene metadata alignment: True\n",
      "miRNA metadata alignment: True\n"
     ]
    }
   ],
   "source": [
    "# Gene expression features and labels\n",
    "X_gene = gene_df.values\n",
    "y_gene = meta_gene[\"label\"].values\n",
    "\n",
    "# miRNA expression features and labels\n",
    "X_mirna = mirna_df.values\n",
    "y_mirna = meta_mirna[\"label\"].values\n",
    "\n",
    "print(\"Gene expression shape:\", X_gene.shape)\n",
    "print(\"miRNA expression shape:\", X_mirna.shape)\n",
    "\n",
    "print(\"\\nGene expression class distribution:\")\n",
    "print(pd.Series(y_gene).value_counts())\n",
    "\n",
    "print(\"\\nmiRNA class distribution:\")\n",
    "print(pd.Series(y_mirna).value_counts())\n",
    "\n",
    "print(\"\\nSample alignment:\", list(gene_df.index) == list(mirna_df.index))\n",
    "print(\"Gene metadata alignment:\", list(gene_df.index) == list(meta_gene.index))\n",
    "print(\"miRNA metadata alignment:\", list(mirna_df.index) == list(meta_mirna.index))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e333d3a1",
   "metadata": {},
   "source": [
    "## Cross-Validation Model Training\n",
    "\n",
    "Because the datasets contain many more features than samples, model performance is evaluated using stratified 5-fold cross-validation.\n",
    "\n",
    "Feature selection and scaling are performed within each cross-validation fold to prevent information leakage.\n",
    "\n",
    "Two classifiers are compared:\n",
    "\n",
    "- Logistic Regression\n",
    "- Random Forest"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "b0a2e575",
   "metadata": {},
   "outputs": [],
   "source": [
    "cv = StratifiedKFold(\n",
    "    n_splits=5,\n",
    "    shuffle=True,\n",
    "    random_state=42\n",
    ")\n",
    "\n",
    "k_features = 500\n",
    "\n",
    "logreg_pipeline = Pipeline([\n",
    "    (\"feature_selection\", SelectKBest(score_func=f_classif, k=k_features)),\n",
    "    (\"scaling\", StandardScaler()),\n",
    "    (\"classifier\", LogisticRegression(max_iter=2000))\n",
    "])\n",
    "\n",
    "rf_pipeline = Pipeline([\n",
    "    (\"feature_selection\", SelectKBest(score_func=f_classif, k=k_features)),\n",
    "    (\"classifier\", RandomForestClassifier(\n",
    "        n_estimators=500,\n",
    "        random_state=42\n",
    "    ))\n",
    "])"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "bde62b5d",
   "metadata": {},
   "source": [
    "### Model Evaluation\n",
    "\n",
    "Generates predictions and probability scores for both Logistic Regression and Random Forest models on gene expression and miRNA datasets."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "7e4f0db9",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Dataset</th>\n",
       "      <th>Model</th>\n",
       "      <th>ROC_AUC_mean</th>\n",
       "      <th>ROC_AUC_std</th>\n",
       "      <th>Accuracy_mean</th>\n",
       "      <th>Accuracy_std</th>\n",
       "      <th>Precision_mean</th>\n",
       "      <th>Recall_mean</th>\n",
       "      <th>F1_mean</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Gene</td>\n",
       "      <td>Logistic Regression</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Gene</td>\n",
       "      <td>Random Forest</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>miRNA</td>\n",
       "      <td>Logistic Regression</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.986667</td>\n",
       "      <td>0.026667</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.977778</td>\n",
       "      <td>0.988235</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>miRNA</td>\n",
       "      <td>Random Forest</td>\n",
       "      <td>0.985185</td>\n",
       "      <td>0.018144</td>\n",
       "      <td>0.919048</td>\n",
       "      <td>0.077606</td>\n",
       "      <td>0.952778</td>\n",
       "      <td>0.908333</td>\n",
       "      <td>0.929150</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  Dataset                Model  ROC_AUC_mean  ROC_AUC_std  Accuracy_mean  \\\n",
       "0    Gene  Logistic Regression      1.000000     0.000000       1.000000   \n",
       "1    Gene        Random Forest      1.000000     0.000000       1.000000   \n",
       "2   miRNA  Logistic Regression      1.000000     0.000000       0.986667   \n",
       "3   miRNA        Random Forest      0.985185     0.018144       0.919048   \n",
       "\n",
       "   Accuracy_std  Precision_mean  Recall_mean   F1_mean  \n",
       "0      0.000000        1.000000     1.000000  1.000000  \n",
       "1      0.000000        1.000000     1.000000  1.000000  \n",
       "2      0.026667        1.000000     0.977778  0.988235  \n",
       "3      0.077606        0.952778     0.908333  0.929150  "
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "results = []\n",
    "\n",
    "results.append(\n",
    "    evaluate_model(\n",
    "        logreg_pipeline,\n",
    "        X_gene,\n",
    "        y_gene,\n",
    "        \"Logistic Regression\",\n",
    "        \"Gene\",\n",
    "        cv\n",
    "    )\n",
    ")\n",
    "\n",
    "results.append(\n",
    "    evaluate_model(\n",
    "        rf_pipeline,\n",
    "        X_gene,\n",
    "        y_gene,\n",
    "        \"Random Forest\",\n",
    "        \"Gene\",\n",
    "        cv\n",
    "    )\n",
    ")\n",
    "\n",
    "results.append(\n",
    "    evaluate_model(\n",
    "        logreg_pipeline,\n",
    "        X_mirna,\n",
    "        y_mirna,\n",
    "        \"Logistic Regression\",\n",
    "        \"miRNA\",\n",
    "        cv\n",
    "    )\n",
    ")\n",
    "\n",
    "results.append(\n",
    "    evaluate_model(\n",
    "        rf_pipeline,\n",
    "        X_mirna,\n",
    "        y_mirna,\n",
    "        \"Random Forest\",\n",
    "        \"miRNA\",\n",
    "        cv\n",
    "    )\n",
    ")\n",
    "\n",
    "results = pd.DataFrame(results)\n",
    "\n",
    "results"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3f4d572f",
   "metadata": {},
   "source": [
    "## Generate Out-of-Fold Predictions\n",
    "\n",
    "Out-of-fold predictions are generated so that each sample is predicted by a model that was not trained on that sample. These predictions are used for downstream ROC curves and confusion matrices."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "ca207b2b",
   "metadata": {},
   "outputs": [],
   "source": [
    "oof_predictions = {}\n",
    "\n",
    "models = {\n",
    "    \"LogReg_Gene\": (logreg_pipeline, X_gene, y_gene),\n",
    "    \"RF_Gene\": (rf_pipeline, X_gene, y_gene),\n",
    "    \"LogReg_miRNA\": (logreg_pipeline, X_mirna, y_mirna),\n",
    "    \"RF_miRNA\": (rf_pipeline, X_mirna, y_mirna)\n",
    "}\n",
    "\n",
    "for name, (model, X, y) in models.items():\n",
    "    \n",
    "    probabilities = cross_val_predict(\n",
    "        model,\n",
    "        X,\n",
    "        y,\n",
    "        cv=cv,\n",
    "        method=\"predict_proba\"\n",
    "    )[:, 1]\n",
    "    \n",
    "    predictions = (probabilities >= 0.5).astype(int)\n",
    "    \n",
    "    oof_predictions[name] = {\n",
    "        \"y_true\": y,\n",
    "        \"y_pred\": predictions,\n",
    "        \"y_prob\": probabilities\n",
    "    }\n",
    "\n",
    "os.makedirs(\"../Results\", exist_ok=True)\n",
    "\n",
    "for name, pred in oof_predictions.items():\n",
    "    \n",
    "    pd.DataFrame({\n",
    "        \"y_true\": pred[\"y_true\"],\n",
    "        \"y_pred\": pred[\"y_pred\"],\n",
    "        \"y_prob\": pred[\"y_prob\"]\n",
    "    }).to_csv(\n",
    "        f\"../Results/{name}_oof_predictions.csv\",\n",
    "        index=False\n",
    "    )"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "55398c98",
   "metadata": {},
   "source": [
    "### Save Model Results\n",
    "\n",
    "Save performance metrics for use in downstream analysis and visualization."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "b47b992b",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Save results to CSV for downstream analysis\n",
    "results.to_csv(\n",
    "    \"../Results/cross_validation_results.csv\",\n",
    "    index=False\n",
    ")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Bioinf_ML",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.20"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
